### ISSUE TITLE
“future feature annotations is not defined (s3.py, line 9)”- When running the example file

### ISSUE THREAD

**Issue by jenny315** [DyogenIBENS/SCORPIOS#11]
Hello, Professor,
The following error occurs when running the example file
```snakemake --configfile config_example.yaml --use-conda --cores 4 --scheduler=greedy```
```
SyntaxError in line 9 of /data/jenny/miniconda3/envs/scorpios/lib/python3.6/site-packages/smart_open/s3.py:
future feature annotations is not defined (s3.py, line 9)
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.6/site-packages/smart_open/__init__.py", line 34, in <module>
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.6/site-packages/smart_open/smart_open_lib.py", line 35, in <module>
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.6/site-packages/smart_open/doctools.py", line 21, in <module>
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.6/site-packages/smart_open/transport.py", line 104, in <module>
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.6/site-packages/smart_open/transport.py", line 49, in register_transport
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.6/importlib/__init__.py", line 126, in import_module
```
I appreciate your quick reply.
Jenny

**Comment by jenny315** [comment]
I check that there is a problem with the python version, so I update python to 3.7.0 and get a new error.

```snakemake --configfile config_example.yaml --use-conda --cores 4 --scheduler=greedy```
``` 
Traceback (most recent call last):
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/snakemake/__init__.py", line 594, in snakemake
    snakefile, overwrite_first_rule=True, print_compilation=print_compilation
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/snakemake/workflow.py", line 1144, in include
    if is_local_file(snakefile):
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/snakemake/common/__init__.py", line 63, in is_local_file
    return parse_uri(path_or_uri).scheme == "file"
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/snakemake/common/__init__.py", line 67, in parse_uri
    from smart_open import parse_uri
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/smart_open/__init__.py", line 34, in <module>
    from .smart_open_lib import open, parse_uri, smart_open, register_compressor  # noqa: E402
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 35, in <module>
    from smart_open import doctools
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/smart_open/doctools.py", line 21, in <module>
    from . import transport
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/smart_open/transport.py", line 101, in <module>
    register_transport("smart_open.gcs")
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/smart_open/transport.py", line 49, in register_transport
    submodule = importlib.import_module(submodule)
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/smart_open/gcs.py", line 15, in <module>
    import google.cloud.storage
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 44, in <module>
    from google.cloud.storage._http import Connection
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 18, in <module>
    from google.cloud import _http
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 26, in <module>
    from google.api_core.client_info import ClientInfo
  File "/data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages/google/api_core/client_info.py", line 34, in <module>
    _GRPC_VERSION = grpc.__version__
AttributeError: module 'grpc' has no attribute '__version__'
```
Then I upgraded 'grpcio'.
```
pip install --upgrade grpcio
```
```
Requirement already satisfied: grpcio in /data/jenny/miniconda3/envs/scorpios/lib/python3.7/site-packages (1.16.0)
Collecting grpcio
  Downloading grpcio-1.62.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 611 kB/s
Installing collected packages: grpcio
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.16.0
    Uninstalling grpcio-1.16.0:
      Successfully uninstalled grpcio-1.16.0
Successfully installed grpcio-1.62.2
```
Then it runs successfully
